[bumpver]
current_version = "0.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true
push = true
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scoop = "global"

[bumpver.file_patterns]
"game/settings/game_settings.py" = [
    '__version__ = "{version}"'
]